"""add column "suffix" for OurImpact Table

Revision ID: 156350d12cc8
Revises: 8b3bceced95c
Create Date: 2024-10-07 17:59:06.959035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156350d12cc8'
down_revision = '8b3bceced95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('our_impact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_suffix', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('our_impact', schema=None) as batch_op:
        batch_op.drop_column('section_suffix')

    # ### end Alembic commands ###
