"""alter column name in AboutUsSection Table

Revision ID: 2705284bb9c4
Revises: dd19f3bd9857
Create Date: 2024-09-23 23:11:00.616239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2705284bb9c4'
down_revision = 'dd19f3bd9857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_us_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_mission_image_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('section_image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_us_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_image_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('section_mission_image_path')

    # ### end Alembic commands ###
