"""add new column to Leadership table

Revision ID: 2b30b251d55a
Revises: 156350d12cc8
Create Date: 2024-10-10 17:07:06.934169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b30b251d55a'
down_revision = '156350d12cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leadership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_management', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leadership', schema=None) as batch_op:
        batch_op.drop_column('is_management')

    # ### end Alembic commands ###
