"""alter column name in AboutUsSection Table

Revision ID: 39ec0dc7e0ce
Revises: bea97b427519
Create Date: 2024-09-24 16:42:54.976898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ec0dc7e0ce'
down_revision = 'bea97b427519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_us_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_vision_image', sa.String(length=255), nullable=True))
        batch_op.drop_column('section_vision_image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_us_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_vision_image_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('section_vision_image')

    # ### end Alembic commands ###
