"""add MissionItems table

Revision ID: 449cd6f2a83c
Revises: fbdd06e36428
Create Date: 2024-09-23 19:53:47.933815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449cd6f2a83c'
down_revision = 'fbdd06e36428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_mission_icon', sa.String(length=150), nullable=True),
    sa.Column('section_mission_body', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mission_items')
    # ### end Alembic commands ###
