"""add table LatestNews

Revision ID: 6fef0c5ca926
Revises: 5e424f99f50b
Create Date: 2024-09-30 13:28:30.854728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fef0c5ca926'
down_revision = '5e424f99f50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latest_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latest_news_title', sa.String(length=200), nullable=True),
    sa.Column('latest_news_body', sa.String(length=1000), nullable=True),
    sa.Column('latest_news_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('latest_news')
    # ### end Alembic commands ###
