"""add new column upcoming event

Revision ID: 8b3bceced95c
Revises: cc00005034d0
Create Date: 2024-09-30 15:24:50.131388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3bceced95c'
down_revision = 'cc00005034d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_title', sa.String(length=200), nullable=True),
    sa.Column('event_image', sa.String(length=255), nullable=True),
    sa.Column('event_body', sa.String(length=1000), nullable=True),
    sa.Column('upcoming_event', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
