"""add table IndustryUpdates

Revision ID: b4862a4200bd
Revises: 6fef0c5ca926
Create Date: 2024-09-30 14:46:38.348016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4862a4200bd'
down_revision = '6fef0c5ca926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_updates_title', sa.String(length=200), nullable=True),
    sa.Column('industry_updates_image', sa.String(length=255), nullable=True),
    sa.Column('inudstry_updates_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('industry_updates')
    # ### end Alembic commands ###
