"""add table Latest Videos

Revision ID: b88338aa7dcc
Revises: 9f2add8f9058
Create Date: 2024-10-15 17:13:44.113314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88338aa7dcc'
down_revision = '9f2add8f9058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latest_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latest_videos_title', sa.String(length=200), nullable=True),
    sa.Column('latest_videos_link', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('latest_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_latest_videos_created_date'), ['created_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_latest_videos_last_modified'), ['last_modified'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('latest_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_latest_videos_last_modified'))
        batch_op.drop_index(batch_op.f('ix_latest_videos_created_date'))

    op.drop_table('latest_videos')
    # ### end Alembic commands ###
