"""alter column name for AboutUsSection Table

Revision ID: bea97b427519
Revises: 2705284bb9c4
Create Date: 2024-09-24 13:50:29.043330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea97b427519'
down_revision = '2705284bb9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_us_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_vision_image_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('section_our_vision_image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_us_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_our_vision_image_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('section_vision_image_path')

    # ### end Alembic commands ###
