"""add Table Leadership

Revision ID: c54ab4422daa
Revises: 39ec0dc7e0ce
Create Date: 2024-09-30 11:06:42.324180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54ab4422daa'
down_revision = '39ec0dc7e0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leadership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leadership_name', sa.String(length=150), nullable=True),
    sa.Column('leadership_titles', sa.String(length=150), nullable=True),
    sa.Column('leadership_position', sa.String(length=150), nullable=True),
    sa.Column('leadership_body', sa.String(length=600), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leadership')
    # ### end Alembic commands ###
