"""change column name in table IndustryUpdates

Revision ID: cc00005034d0
Revises: b4862a4200bd
Create Date: 2024-09-30 14:57:16.249032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc00005034d0'
down_revision = 'b4862a4200bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('industry_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry_updates_link', sa.String(length=255), nullable=True))
        batch_op.drop_column('inudstry_updates_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('industry_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inudstry_updates_link', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('industry_updates_link')

    # ### end Alembic commands ###
