"""add Table ValuesItems

Revision ID: dd19f3bd9857
Revises: 449cd6f2a83c
Create Date: 2024-09-23 19:54:12.388286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd19f3bd9857'
down_revision = '449cd6f2a83c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('values_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_our_values_icon', sa.String(length=150), nullable=True),
    sa.Column('section_our_values_body', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('values_items')
    # ### end Alembic commands ###
