"""set string length to 1000 for AboutUsSection Body

Revision ID: f685bc9b5ba1
Revises: b88338aa7dcc
Create Date: 2024-12-12 22:00:36.730624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f685bc9b5ba1'
down_revision = 'b88338aa7dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_us_section', schema=None) as batch_op:
        batch_op.alter_column('section_about_us_body',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_us_section', schema=None) as batch_op:
        batch_op.alter_column('section_about_us_body',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###
