"""add Table for the general About Us Section

Revision ID: fbdd06e36428
Revises: 9a704b1a1fb6
Create Date: 2024-09-23 19:53:23.021225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbdd06e36428'
down_revision = '9a704b1a1fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_us_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_about_us_title', sa.String(length=150), nullable=True),
    sa.Column('section_about_us_body', sa.String(length=400), nullable=True),
    sa.Column('section_about_us_image_path', sa.String(length=255), nullable=True),
    sa.Column('section_mission_title', sa.String(length=150), nullable=True),
    sa.Column('section_image_path', sa.String(length=255), nullable=True),
    sa.Column('section_our_vision_title', sa.String(length=150), nullable=True),
    sa.Column('section_our_vision_body', sa.String(length=400), nullable=True),
    sa.Column('section_our_vision_image_path', sa.String(length=255), nullable=True),
    sa.Column('section_our_values_title', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about_us_section')
    # ### end Alembic commands ###
